name: Deployment		
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Test Project
        run: mvn test --file pom.xml
      - name: Upload Test Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: Coverage-Report
          path: |
            target/site/jacoco
      - name: Upload UI Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: UI-Test-Screenshots
          path: |
            target/screenshots
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Build Project
        run: mvn package --file pom.xml
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}		
      - name: Docker Build and Push to DockerHub
        run: |
          docker build -t rameshs24/contactlistapp:latest .
          docker push rameshs24/contactlistapp:latest	