name: Deployment		
on: workflow_dispatch
jobs:
  build-and-deploy:
  runs-on: ubuntu-latest	
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'		
    - name: Build Project
      run: mvn package --file pom.xml
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}		
    - name: Docker Build and Push to DockerHub
      run: |
        docker build -t rameshs24/contactlistapp:latest .
        docker push rameshs24/contactlistapp:latest	